# https://stackoverflow.com/questions/38298645/how-should-i-backup-restore-docker-named-volumes

parameters:
  - name: environment
    type: string
  - name: inputFolder
    type: string

jobs:
  - deployment: restoreData
    environment:
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    variables:
      backupFolder: /backup
      backupFileName: data.tar.gz
    strategy:
      runOnce:
        deploy:
          steps:
            - script: cp ${{ parameters.inputFolder }}/$(backupFileName) $(Build.SourcesDirectory)
            - script: docker run --rm --volume rusetfs-blog_data:$(backupFolder)/source --volume $(Build.SourcesDirectory):$(backupFolder)/target ubuntu bash -c "cd $(backupFolder);tar xfz target/$(backupFileName) source"
  - deployment: restoreContent
    environment:
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    variables:
      backupFolder: /backup
      backupFileName: content.tar.gz
    strategy:
      runOnce:
        deploy:
          steps:
            - script: cp ${{ parameters.inputFolder }}/$(backupFileName) $(Build.SourcesDirectory)
            - script: docker run --rm --volume rusetfs-blog_content:$(backupFolder)/source --volume $(Build.SourcesDirectory):$(backupFolder)/target ubuntu bash -c "cd $(backupFolder);tar xfz target/$(backupFileName) source"