# https://stackoverflow.com/questions/38298645/how-should-i-backup-restore-docker-named-volumes

# Назначение: восстановить данные на тачке
# Как работате: в текущем деплое данные хранятся внутри контейнера. Что бы их восстановить мы просто копируем их извне
# Для работы в папку на внешней тачке (где идет запуск, см inputFolder) нужно положить 2 файла с бекапом, созданный бекап-пайплайном

parameters:
  - name: environment
    type: string
  - name: inputFolder
    type: string

jobs:
  - deployment: restoreData
    environment:
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    variables:
      backupFolder: /backup
      backupFileName: data.tar.gz
    strategy:
      runOnce:
        deploy:
          steps:
            - script: cp ${{ parameters.inputFolder }}/$(backupFileName) $(Build.SourcesDirectory)
            - script: docker run --rm --volume rusetfs-blog_data:$(backupFolder)/source --volume $(Build.SourcesDirectory):$(backupFolder)/target ubuntu bash -c "cd $(backupFolder);tar xfz target/$(backupFileName) source"
  - deployment: restoreContent
    environment:
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    variables:
      backupFolder: /backup
      backupFileName: content.tar.gz
    strategy:
      runOnce:
        deploy:
          steps:
            - script: cp ${{ parameters.inputFolder }}/$(backupFileName) $(Build.SourcesDirectory)
            - script: docker run --rm --volume rusetfs-blog_content:$(backupFolder)/source --volume $(Build.SourcesDirectory):$(backupFolder)/target ubuntu bash -c "cd $(backupFolder);tar xfz target/$(backupFileName) source"