pool:
  vmImage: 'Ubuntu 16.04'

variables:
  dockerRegistry: 'AnotherICe - Docker - Registry'
  dockerRepostiory: anotherice/rusetfs-blogifier

steps:
- task: Docker@2
  inputs:
    command: login
    containerRegistry: $(dockerRegistry)
- task: Docker@2 
  inputs:
    command: buildAndPush
    containerRegistry: $(dockerRegistry)
    repository: $(dockerRepostiory)
    arguments: '--target run'
    dockerfile: dockerfile