trigger: 
- master

pool:
  vmImage: 'Ubuntu 20.04'

stages:
  - stage: staging
    jobs:
      - template: templates/backup/job.yml
  - stage: production
    jobs:
      - template: templates/backup/job.yml