version: "3.9"
services:
  app:
    image: anotherice/rusetfs-blogifier:${RUSETFS_BLOGIFIER_APP_VERSION}
    ports: 
      - 20000:80
    volumes:
      - ${RUSETFS_BLOGIFIER_DATA_DIR}\data.sqlite:/app/Blog.db
      - ${RUSETFS_BLOGIFIER_DATA_DIR}\wwwroot\data:/app/wwwroot/data
