version: "3.9"
services:
  app:
    image: anotherice/rusetfs-blogifier:${RUSETFS_BLOGIFIER_APP_VERSION}
    ports: 
      - 20000:80
    volumes:
      - ${RUSETFS_BLOGIFIER_DATA_DIR}\blog.db:/app/Blog.db
      - ${RUSETFS_BLOGIFIER_DATA_DIR}\data:/app/wwwroot/data
