parameters:
  - name: dockerComposeArtifact
    type: string

jobs:
  - job: buildDockerComposeArtifact
    pool:
      name: Default
    steps:
      - publish: $(Build.SourcesDirectory)/.azure/release/templates/build-artifacts/resources/docker-compose.yml
        artifact: $(dockerComposeArtifact)
