trigger: 
- master

pool:
  vmImage: 'Ubuntu 20.04'

variables:
  dockerRegistry: 'AnotherICe - Docker - Registry'
  dockerRepostiory: anotherice/petproject03-blog
  dockerComposeArtifact: dockerCompose

stages:
  - stage: build
    jobs:
      - template: templates/build-images/job.yaml
        parameters:
          dockerRegistry: $(dockerRegistry)
          dockerRepostiory: $(dockerRepostiory)
        - template: templates/build-artifacts/job.yaml
          parameters:
            dockerComposeArtifact: $(dockerComposeArtifact)
  - stage: staging
    jobs:
      - template: templates/deploy-docker-compose/job.yml
        parameters:
          environment: Staging
          dockerRegistry: $(dockerRegistry)
          dockerRepostiory: $(dockerRepostiory)
          dockerComposeArtifact: $(dockerComposeArtifact)
  - stage: production
    jobs:
      - template: templates/deploy-docker-compose/job.yml
        parameters:
          environment: Production
          dockerRegistry: $(dockerRegistry)
          dockerRepostiory: $(dockerRepostiory)
          dockerComposeArtifact: $(dockerComposeArtifact)
