version: "3.9"
services:
  app:
    image: ${RUSETFS_BLOGIFIER_APP}
    restart: always
    ports: 
      - 20000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${RUSETFS_BLOGIFIER_ENVIRONMENT}
      - APP_BLOGIFIER__CONNSTRING=/app/data/Blog.db
    volumes:
      - data:/app/data
      - content:/app/wwwroot/data

volumes:
  data:
  content: