version: "3.9"

services:
  app:
    image: ${RUSETFS_BLOGIFIER_APP}
    restart: always
    ports: 
      - 20000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${RUSETFS_BLOGIFIER_ENVIRONMENT}
      - APP_BLOGIFIER__CONNSTRING=DataSource=/app/data/Blog.db
    volumes:
      - data:/app/data
      - content:/app/wwwroot/data
      - ${BACKUP_FOLDER}:/backup
    networks:
      - rusetfs
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.blog-backup.schedule: "0 0 3 * * *"
      ofelia.job-exec.blog-backup.command: bash -c "cd /app;tar cfz /backup/$$(date +\"%m_%d_%Y__%H_%M_%S\")_blog_content.tar.gz wwwroot/data;tar cfz /backup/$$(date +\"%m_%d_%Y__%H_%M_%S\")_blog_data.tar.gz data;"
      traefik.enable: "true"
      traefik.http.routers.blog-outer.rule: HostRegexp(blog.*)
      traefik.http.routers.blog-outer.priority: 55
      

volumes:
  data:
  content:

networks:
  rusetfs:
    name: rusetfs
    external: true
