version: "3.9"

services:
  app:
    image: ${RUSETFS_BLOGIFIER_APP}
    restart: always
    ports: 
      - 20000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${RUSETFS_BLOGIFIER_ENVIRONMENT}
      - APP_BLOGIFIER__CONNSTRING=DataSource=/app/data/Blog.db
    volumes:
      - data:/app/data
      - content:/app/wwwroot/data
    networks:
      - rusetfs
    labels:
      ofelia.enabled: true
      ofelia.job-run.blog-backup.schedule: "@every 1m"
      ofelia.job-run.blog-backup.image: ubuntu
      ofelia.job-run.blog-backup.volume: ["rusetfs-blog_data:/backup/source/data", "/home/rusetfs/backup/blog:/backup/target"]
      ofelia.job-run.blog-backup.command: "cd /backup/source;tar cfz target/$(date + \"%m_%d_%Y__%H_%M_%S\")_blog_data.tar.gz source/data;"

volumes:
  data:
  content:

networks:
  rusetfs:
    name: rusetfs
    external: true