version: "3.9"

services:
  app:
    image: ${RUSETFS_BLOGIFIER_APP}
    restart: always
    ports: 
      - 20000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${RUSETFS_BLOGIFIER_ENVIRONMENT}
      - APP_BLOGIFIER__CONNSTRING=DataSource=/app/data/Blog.db
    volumes:
      - data:/app/data
      - content:/app/wwwroot/data
      - /home/rusetfs/backup/blog:/backup
    networks:
      - rusetfs
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.blog-backup.schedule: "@every 1m"
      ofelia.job-exec.blog-backup.command: bach -c "cd /app;tar cfz /backup/$$(date +\"%m_%d_%Y__%H_%M_%S\")_blog_content.tar.gz wwwroot/data;tar cfz /backup/$$(date +\"%m_%d_%Y__%H_%M_%S\")_blog_data.tar.gz data;"

volumes:
  data:
  content:

networks:
  rusetfs:
    name: rusetfs
    external: true