parameters:
  - name: dockerRegistry
    type: string
  - name: dockerRepostiory
    type: string

jobs:
  - job: buildServiceDockerImage
    pool:
      name: Default
    steps:
      - task: Docker@2
        inputs:
          command: login
          containerRegistry: $(dockerRegistry)
      - task: Docker@2
        inputs:
          command: buildAndPush
          containerRegistry: $(dockerRegistry)
          repository: $(dockerRepostiory)
          arguments: '--target server'
          dockerfile: $(Build.SourcesDirectory)/.azure/release/templates/build-images/resources/service.dockerfile
          buildContext: .