parameters:
  - name: environment
    type: string
  - name: dockerRegistry
    type: string
  - name: dockerRepostiory
    type: string
  - name: dockerComposeArtifact
    type: string

jobs:
  - deployment: deployOnDockerCompose
    environment:
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Docker@2
              inputs:
                command: login
                containerRegistry: $(dockerRegistry)
            - task: DownloadPipelineArtifact@2
              inputs:
                artifactName: $(dockerComposeArtifact)
                targetPath: $(Build.SourcesDirectory)
            - task: DockerCompose@0
              inputs:
                action: Run services
                containerregistrytype: Container Registry
                dockerRegistryEndpoint: $(dockerRegistry)
                dockerComposeFile: $(Build.SourcesDirectory)/docker-compose.yml
                buildImages: false
                projectName: rusetfs-blog
                dockerComposeFileArgs: |
                  RUSETFS_BLOGIFIER_APP=$(dockerRepostiory):$(Build.BuildId)
                  RUSETFS_BLOGIFIER_ENVIRONMENT=$(environment)