trigger: none

# Назначение: восстановить бекап данных

pool:
  vmImage: 'Ubuntu 20.04'

stages:
  - stage: staging
    jobs:
      - template: templates/restore/job.yml
        parameters:
          environment: Staging
          inputFolder: /home/rusetfs/backup/blog
  - stage: production
    jobs:
      - template: templates/restore/job.yml
        parameters:
          environment: Production
          inputFolder: /home/rusetfs/backup/blog