trigger: none  

pool:
  vmImage: 'Ubuntu 20.04'

stages:
  - stage: staging
    jobs:
      - template: templates/restore/job.yml
        parameters:
          environment: Staging
          inputFolder: /rusetfs/backup/blog
  - stage: production
    jobs:
      - template: templates/restore/job.yml
        parameters:
          environment: Production
          inputFolder: /rusetfs/backup/blog