trigger: none  

pool:
  vmImage: 'Ubuntu 20.04'

stages:
  - stage: staging
    jobs:
      - template: templates/restore/job.yml
        parameters:
          environment: Staging
  - stage: production
    jobs:
      - template: templates/restore/job.yml
        parameters:
          environment: Production