# https://stackoverflow.com/questions/38298645/how-should-i-backup-restore-docker-named-volumes

parameters:
  - name: dockerComposeArtifact
    type: string

jobs:
  - job: backupData
    pool:
      name: Default
    variables:
      backupFolder:/backup
      backupDataFileName:data_$[format('{0:yyyyMMdd_hhmmss}', pipeline.startTime)].tar.gz
    steps:
      - script: docker run --rm --volume rusetfs-blog_data:$(backupFolder)/source --volume $(pwd):$(backupFolder)/target ubuntu bash -c "cd $(backupFolder);tar cfz target/$(backupDataFileName) source" 