# https://stackoverflow.com/questions/38298645/how-should-i-backup-restore-docker-named-volumes

parameters:
  - name: environment
    type: string

jobs:
  - deployment: backupData
    environment:
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    variables:
      backupFolder: /backup
      backupFileName: data.tar.gz
    strategy:
      runOnce:
        deploy:
          steps:
            - script: docker run --rm --volume rusetfs-blog_data:$(backupFolder)/source --volume $(Build.SourcesDirectory):$(backupFolder)/target ubuntu bash -c "cd $(backupFolder);tar cfz target/$(backupFileName) source"
            - publish: $(Build.SourcesDirectory)/$(backupFileName)
              artifact: $(backupFileName)
  - deployment: backupContent
    environment:
      name: ${{ parameters.environment }}
      resourceType: VirtualMachine
    variables:
      backupFolder: /backup
      backupFileName: content.tar.gz
    strategy:
      runOnce:
        deploy:
          steps:
            - script: docker run --rm --volume rusetfs-blog_content:$(backupFolder)/source --volume $(Build.SourcesDirectory):$(backupFolder)/target ubuntu bash -c "cd $(backupFolder);tar cfz target/$(backupFileName) source"
            - publish: $(Build.SourcesDirectory)/$(backupFileName)
              artifact: $(backupFileName)
      